name: Build & Deploy (Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # instala dependencias (usa ci si hay package-lock; si falla, npm i)
      - run: npm ci || npm i --no-audit --no-fund
      # compila Tailwind v4 desde tu archivo actual
      - run: npx @tailwindcss/cli -i ./src/styles/tailwind.css -o ./src/styles/output.css -m
      # sube el sitio estático (todo el repo)
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
